### ISSUE TITLE
Update task-6 to use sock, instead of conn

### ISSUE THREAD

**Issue by smlng** [RIOT-OS/Tutorials#28]
Task-06 still uses the - now deprecated - conn API, which should be updated to sock. Further, the README show the shell command `txtsnd` which is not present anymore, see #26.

**Comment by smlng** [comment]
btw. `conn` is actually removed already from RIOT
```

/Volumes/workspace/github/RIOT-OS/Tutorials/task-06/udp.c:6:10: fatal error: 'net/conn/udp.h' file not found
#include "net/conn/udp.h"
         ^

```

**Comment by miri64** [comment]
See #29
