### ISSUE TITLE
Cannot build example 2 

### ISSUE THREAD

**Issue by SoniaZotz** [RIOT-OS/Tutorials#30]
/home/vagrant/RIOT/Tutorials/task-02/main.c: In function 'echo':
/home/vagrant/RIOT/Tutorials/task-02/main.c:7:14: error: unused parameter 'argc' [-Werror=unused-parameter]
 int echo(int argc, char **argv)
              ^
/home/vagrant/RIOT/Tutorials/task-02/main.c:7:27: error: unused parameter 'argv' [-Werror=unused-parameter]
 int echo(int argc, char **argv)
                           ^
cc1: all warnings being treated as errors
/home/vagrant/RIOT/Makefile.base:81: recipe for target '/home/vagrant/RIOT/Tutorials/task-02/bin/native/Task02/main.o' f
ailed
make[1]: *** [/home/vagrant/RIOT/Tutorials/task-02/bin/native/Task02/main.o] Error 1
/home/vagrant/RIOT/Tutorials/task-02/../..//Makefile.include:301: recipe for target 'all' failed
make: *** [all] Error 2
vagrant@vagrant:~/RIOT/Tutorials/task-02$

**Comment by kYc0o** [comment]
Did you solve your problem?

**Comment by SoniaZotz** [comment]
no - I thought I did 

vagrant@vagrant:~/RIOT/Tutorials/task-02$ make
Building application "Task02" for "native" with MCU "native".

/home/vagrant/RIOT/Tutorials/task-02/main.c: In function 'echo':
/home/vagrant/RIOT/Tutorials/task-02/main.c:7:14: error: unused parameter 'argc' [-Werror=unused-parameter]
 int echo(int argc, char **argv)
              ^
/home/vagrant/RIOT/Tutorials/task-02/main.c:7:27: error: unused parameter 'argv' [-Werror=unused-parameter]
 int echo(int argc, char **argv)
                           ^
cc1: all warnings being treated as errors
/home/vagrant/RIOT/Makefile.base:81: recipe for target '/home/vagrant/RIOT/Tutorials/task-02/bin/native/Task02/main.o' f
ailed
make[1]: *** [/home/vagrant/RIOT/Tutorials/task-02/bin/native/Task02/main.o] Error 1
/home/vagrant/RIOT/Tutorials/task-02/../..//Makefile.include:301: recipe for target 'all' failed
make: *** [all] Error 2
vagrant@vagrant:~/RIOT/Tutorials/task-02$

**Comment by kYc0o** [comment]
Well, looking at the tutorial, that's normal, since the function is empty purposely. The goal is to fill the function with the required instructions to extend the shell command.

Can you try to do the exercise and see if it compiles?

**Comment by SoniaZotz** [comment]
I thought this was a tutorial - not an exam  I'm lost and was looking to use these examples  to get started 
what do working code for both tasks look like  

what is meant by ie: Extend the echo() function in main.c to print the first argument to the command handler
int cmd_handler(int argc, char **argv);  ????

**Comment by smlng** [comment]
Hi @SoniaZotz, first: welcome to RIOT! And second: hope you are not too frustrated with our tutorials, yet?! So, let me try to give you some hints without writing down the solution directly, though its not exam this tutorial is still meant to be an excersice (with several small (sub)tasks) to get to know RIOT-OS.

Btw. for working examples, have a look into the RIOT main repository under [examples](https://github.com/RIOT-OS/RIOT/tree/master/examples).

----

Now to the problem at hand here:

> Extend the echo() function 

```
int echo(int argc, char **argv)
{
    /* ... */
    return 0;
}
```

as you see the function does nothing, which is also why you get the error `unused variable`. What you need to do is put some code there that uses `argc` and `argv` <- these should look familiar from typical C examples with a simple `main(...)` function. The task is to print the first argument which is passed to that function, `argc` gives you the number of elements (arguments) in `argv`, hence you can check how many (if any) are available for printing.

To make the command available to the shell you need to extend the `commands[]` array to provide a handle for `echo()` - as shown in the task description.

**Comment by smlng** [comment]
@SoniaZotz please let us know if you succeeded with the task (and we can close this issue) or need any further help.

**Comment by PeterKietzmann** [comment]
After many people complained about that I just decided to merge #47 which 'fixes' this issue
