### ISSUE TITLE
Task 6&7, cannot establish connection between Linux and Native

### ISSUE THREAD

**Issue by yfan41** [RIOT-OS/Tutorials#39]
Environment:
64-bit linux(17.04)

In task 6:
After setting up server using udps 8888.
Calling `echo "hello" | nc -6u <RIOT-IPv6-addr>%tapbr0 8888` from Linux doesn't print "hello" on Native instance. I also tried to debug it by using a wrong ipv6 address for `<RIOT-IPv6-addr>`, no errors or warnings were given on Linux.

In task 7:
`ping6 <RIOT-IPv6-addr>%tapbr0`
gives error
`ping: e83e:78ff:fe83:7c17%tap0: Name or service not known`.

**Comment by smlng** [comment]
> `e83e:78ff:fe83:7c17%tap0`

this isn't a valid (link-local) IPv6 address, the prefix is missing, i.e., `fe80::`

**Comment by PeterKietzmann** [comment]
@smlng explained what was mistaken -> I'm closing this one now. @yfan41 please reopen the issue still persists
