### ISSUE TITLE
Figure should display sock (instead of conn)

### ISSUE THREAD

**Issue by emmanuelsearch** [RIOT-OS/Tutorials#41]
In the [figure](https://github.com/RIOT-OS/Tutorials/blob/master/overview-net.png) displayed in Task 5&6, the north-bound interface needs to be updated to show sock, instead of deprecated conn.

**Comment by miri64** [comment]
Fixed by #37 (@OlegHahm ping?)

**Comment by miri64** [comment]
#37 was merged
