### ISSUE TITLE
Task-08 cannot download tlsf-3.0.zip

### ISSUE THREAD

**Issue by rl1987** [RIOT-OS/Tutorials#46]
In task 08 `make all term` gets stuck at:
```
/home/vagrant/Tutorials/RIOT/dist/tools/dlcache/dlcache.sh: "/home/vagrant/.dlcache/tlsf-3.0.zip" has wrong checksum, re-downloading
/home/vagrant/Tutorials/RIOT/dist/tools/dlcache/dlcache.sh: downloading "http://download.riot-os.org/tlsf-3.0.zip"...
```

It seems that download.riot-os.org is down.

**Comment by miri64** [comment]
That server is AFAIK under [maintainance at the moment](https://lists.riot-os.org/pipermail/devel/2018-August/005901.html). Should be back up tomorrow at the latest.

**Comment by tcschmidt** [comment]
Server is up again.
