### ISSUE TITLE
drivers: interoperability of 802.15.4 radios

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/Tutorials#53]
1. We should incorporate all 802.15.4 radios in our release tests.
2. We should add interoperability tests between different radios.

Especially when it comes to 6LoWPAN fragmentation where multiple frames are sent subsequently, I expect many issues. Just as an example, in [#9864](https://github.com/RIOT-OS/RIOT/pull/9864) I found out that `ping6` with fragmented ICMPv6 packets results in 100% loss between cc2538 and mrf24j40 radios.

**Comment by aabadie** [comment]
Basic interoperability tests are included in the release phase but only between iotlab-m3, samr21-xpro, arduino-zero/XBee and remote-reva/b. Except for the remote, all these tests can be run on IoT-LAB, and more precisely on the Saclay site: a dozen iotlab-m3, 15 samr21-xpro and 3 arduino-zero are there in the same room and can communicate between each other.
And in a close future (expect 2 to 4 weeks), there will be frdm-kw41z and nrf52840dk (and I'm thinking about adding samr30-xpro as well. All in the same room and easily reachable from the RIOT build system thanks to the awesome IOTLAB_NODE variable !

**Comment by miri64** [comment]
Shouldn't this be discussed in the Release-Specs repository and not the Tutorials repository? ;-)

**Comment by PeterKietzmann** [comment]
Whoops. Moved to [Release Specs Repository](https://github.com/RIOT-OS/Release-Specs/issues/74)

**Comment by PeterKietzmann** [comment]
Whoops. Moved to [Release Specs Repository](https://github.com/RIOT-OS/Release-Specs/issues/74)
