### ISSUE TITLE
task-05 ipconfig not available

### ISSUE THREAD

**Issue by paxter** [RIOT-OS/Tutorials#54]
I just did task 5.1 and everything works until the ipconfig command.
Looks like ipconfig is not available:

```
> ipconfig
ipconfig
shell: command not found: ipconfig
```

I followed the tutorial and did all previous tasks. I'm on OSX.

**Comment by miri64** [comment]
The command is called `ifconfig`. The task says as much, so I'm closing the issue.

**Comment by paxter** [comment]
Oh, sorry. Didn't notice that. :/
