### ISSUE TITLE
Wrong include path

### ISSUE THREAD

**Issue by plushvoxel** [RIOT-OS/Tutorials#8]
### Expected behavior

succesful compilation
### Actual behavior

`fatal error: gnrc/net/netreg.h: No such file or directory`
### Test code

``` c
#include "gnrc/net/netreg.h"
```
### RIOT version

RIOT @ 6b768a1
### Hardware

native

**Comment by miri64** [comment]
Could you point me to the task?

**Comment by miri64** [comment]
https://github.com/RIOT-OS/Tutorials/commit/f99093012d51294ce8f27b92ee731c8a40fa9c5c should fix it.
