### ISSUE TITLE
undeclared sched_active_pid

### ISSUE THREAD

**Issue by plushvoxel** [RIOT-OS/Tutorials#9]
### Expected behavior

succesful compilation
### Actual behavior

```
error: ‘sched_active_pid’ undeclared (first use in this function)
    gnrc_netreg_entry_t server = {NULL, 8888, sched_active_pid};
```
### Test code

``` c
int main(void){
    ...
    gnrc_netreg_entry_t server = {NULL, 8888, sched_active_pid};
    gnrc_netreg_register(GNRC_NETTYPE_UDP, &server);
    ...
    return 0;
}
```
### RIOT version

RIOT @ 6b768a1
### Hardware

native
### Quick Fix

``` c
#include "sched.h"
```

**Comment by miri64** [comment]
Not only quick fix, but actual fix ;-) Don't be afraid to provide a PR against this repo ;-)

**Comment by miri64** [comment]
and https://github.com/RIOT-OS/Tutorials/commit/a6a5416b291358c78b3021f81fec23598b0e5adc
